### ISSUE TITLE
The row for message topics is too tall for moderators due to line 65

### ISSUE THREAD

**Issue by jay010** [kayakyakr/rivals-board-enhancements#1]
I'm sure there was a reason for line 65, but I can't see what it was intended to improve. However, when moderators view the board, the "Edit" link is no longer able to float to the right of the .posterDate element, which increases the height of the row. Obviously this link doesn't show and therefore isn't an issue for regular members. However, without knowing the original reason for line 65, I can't offer up much of a solution, but it would perform better for moderators if you can remove the line altogether.

Line 65
.discussionListItem .listBlock .secondRow .posterDate {
  float: none;
}

Here is what it currently renders:
![image](https://cloud.githubusercontent.com/assets/7359622/7265993/aa84fdd2-e868-11e4-93df-568cd9b3bc99.png)
vs.
![image](https://cloud.githubusercontent.com/assets/7359622/7265999/c2f3dc80-e868-11e4-950d-03dbf14875bf.png)

**Comment by kayakyakr** [comment]
I'll check in to it.

**Comment by kayakyakr** [comment]
The purpose of that line was an alignment issue. When the row was floated left (as it is originally), it moves out of alignment with the link row and will often wrap in terrible, undesired ways. If you could figure out how to get the alignment or float the edit button in a desired way, then I'll put that in. For now, I'm going to provide an option to turn it off.

If you run across anything else that doesn't work for moderators, let me know.
